blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [

    # path('' , views.post_list , name='post_list') ,

    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('<int:post_id>/share/' , views.post_share , name='post_share')



]

myblog/urls.py
from django.contrib import admin
from django.urls import path , include
from blog import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls')),
    # path('' , views.post_list , name='post_list') ,
    # path('', views.PostListView.as_view(), name='post_list'),
    path('' , views.PostListView.as_view() , name='post_list'),
    
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse , reverse_lazy

# Create your models here.

class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager , self).get_queryset().filter(status = 'published')


class Post(models.Model):
    STATUS_CHOICES = (
            ('draft' , 'Draft'),
            ('published' , 'Published'),
    ) 
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User , on_delete=models.CASCADE , related_name='blog_post')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10 , choices=STATUS_CHOICES , default='draft')
    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail' ,
         args=[self.publish.year ,
          self.publish.month , 
          self.publish.day , 
          self.slug])

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    class Meta:
        ordering = ('-created',)
    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
from django import forms
from django.forms import fields
from .models import Comment
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name' , 'email' , 'body')

blog/views.py
from django.views.generic import ListView
from blog.models import Post
from django.shortcuts import render, get_object_or_404, HttpResponse
from .models import Post
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm , CommentForm
from django.core.mail import message, send_mail

# Create your views here.


def post_list(request):
    object_list = Post.published.all()
    paginator = Paginator(object_list, 3)  # 3 pages in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # if page is not a integer deliver the first page
        posts = paginator.page(1)

    except EmptyPage:
        # If page us out of rage deliver last page of result
        posts = paginator(paginator.num_pages)

    # posts = Post.published.all()
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published',
                             publish__year=year, publish__month=month, publish__day=day)

                             # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
    # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    return render(request, 'blog/post/detail.html', {'post': post , 'comments' : comments , 'new_comments' : new_comment , 'comment_form' : comment_form} )

# def index(request):
#     return HttpResponse("Hello Index page")


class PostListView(ListView):
    queryset = Post.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'





def post_share(request, post_id):


    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')  
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.title)
            message= 'Read "{}" at {}\n\n{}\'s comments:{}'.format(post.title, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'mydjango19@gmail.com',[cd['to']])
            sent=True
    else:
        form=EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,'form': form,'sent': sent})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>{% block title %}{% endblock %}</title>

<link href="{% static "css/style.css" %}" rel="stylesheet">
<link href="https://fonts.googleapis.com/css2?family=Bree+Serif&family=Pacifico&display=swap" rel="stylesheet">
    <!--  M icons -->
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
<!--  M Compiled and minified CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
</head>
<body>

<section>
<div  class = "fnavbar">
        
  <nav class="nav-fixed">
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">MyBlog</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger"><i class="side material-icons">menu</i></a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li> 
      </ul>
    </div>
    
  </nav>

  <ul class="sidenav" id="mobile-demo">
    <li><a href="#">Home</a></li>
        <li><a href="#">About</a></li>
        <li><a href="#">Contact</a></li>
  </ul>


</div>
</section>

<div id="content">
{% block content %}
{% endblock %}
</div>
{% comment %} <div id="sidebar">
<h2>My blog</h2>
<p>This is my blog.</p>
</div> {% endcomment %}
</body>
{% block body%}

{% endblock%}

{% comment %} <section class  = 'fparallax'>
    <div class="parallax-container">
      <div class="parallax"><img src="{% static 'images/blog-slogan.jpg' %}" alt="image1">
    </div>
</section> {% endcomment %}


<section class = 'features'>
  <div class = 'container'>
      <div class = 'row'>
            <div class = 'col l3 s6 m6'>
                <div >
                  <i class="large material-icons">share</i>
                  <p class='share'>You can share it</p>
                </div>
            </div>
            <div class = 'col l3 s6 m6'>
                <div >
                  <i class="large material-icons">local_library</i>
                  <p class='share'>you can read it</p>
                </div>
            </div>
            <div class = 'col l3 s6 m6'>
                <div >
                  <i class="large material-icons">local_library</i>
                  <p class='share'>you can read it</p>
                </div>
            </div>

            <div class = 'col l3 s6 m6'>
                <div >
                  <i class="large material-icons">insert_comment</i>
                  <p class='share'>You can comment out</p>
                </div>
            </div>
    </div>
  </div>
</section>
        
<section class = 'ffooter'>
    <footer class = 'footer-one'>
        <div class='container'>
            <div class = 'row'>
                <div class = 'col l4 s12 '>
                    <h4 class ='white-text '>Contact Us</h4>
                    <p class  = 'white-text'>
                        ABC 507 , Mumbai , India
                    </p>
                    <p class   ='white-text '>
                       +919787969513
                    </p>

                </div>
                <div class = 'col l4 s12 '>
                    <h4 class ='white-text '>About Us</h4>
                    <ul>
                            <li><a href = '#' class = 'white-text'>Mylog</a></li>
                            <li><a href = '#' class = 'white-text'>Django</a></li>
                            <li><a href = '#' class = 'white-text'>Sqlite3</a></li>
                    </ul>

                </div>
                <div class ='col l4 sm12  '>
                    <h4 class ='white-text '>Social Media</h4>
                        <ul>
                            <li><a href = '#' class = 'white-text'>Facebool</a></li>
                            <li><a href = '#' class = 'white-text'>Instagram</a></li>
                            <li><a href = '#' class = 'white-text'>Twitter</a></li>
                        </ul>

                </div>

            </div>
            
        </div>
        <div class = 'row footer-two' >
                <div  class = 'col l4 sm12 left-align '>
                    <p class = 'white-text'>&copy;Myblog
                    </p>

                </div>
                <div  class = 'col l4 sm12 center-align '>
                    <p class = 'white-text'>Django❤
                    </p>

                </div>
                <div class  = 'col l4 sm12 right-align '>
                    <p class = 'white-text'>Desighed by Girish
                    </p>
                </div>
            </div>

    </footer>

</section>


{% block script %}
<script>
</script

{% endblock %}

<!-- jquery -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<!-- M Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
<!-- custom js -->
<script src="{% static "script/loader.js" %}"></script>

</html>

blog/templates/blog/pagination.html
{% comment %} <div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
    <span class="current">
    Page {{ page.number }} of {{ page.paginator.num_pages }}.
    </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div> {% endcomment %}

<div class ='pagination1'>
    <ul class="pagination">
    
        <span class="step-links">
            {% if page.has_previous %}
                <li class="waves-effect"><a href="?page={{ page.previous_page_number }}"><i class="material-icons">chevron_left</i></a></li></a>
            {% endif %}
                    <span class="current">
                    Page{{ page.number }} of {{ page.paginator.num_pages }}.
                    </span>
            {% if page.has_next %}
                <li class="waves-effect"><a href="?page={{ page.next_page_number }}"><i class="material-icons">chevron_right</i></a></li></a>
            {% endif %}
        </span>
    
    
    </ul>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
<div class = 'container '>
        <h1 class  = 'blogTitle center-align'>{{ post.title }}</h1>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|linebreaks }}
        <p>
        <a href="{% url "blog:post_share" post.id %} " class  = 'center-align'>Share this post </a>
        </p>

        <section class = 'preComment'>
                {% with comments.count as total_comments %}
                <h2 class = 'countComment'>
                {{ total_comments }} comment{{ total_comments|pluralize }}
                </h2>
                {% endwith %}

                    {% for comment in comments %}
                    <div class="comment">
                    <p class="info">
                    Comment {{ forloop.counter }} by {{ comment.name }}
                    {{ comment.created }}
                    </p>
                    {{ comment.body|linebreaks }}
                    </div>
                    {% empty %}
                    <p>There are no comments yet.</p>
                    {% endfor %}

        </section>


        <section>
                    {% if new_comment %}
                    <h2>Your comment has been added.</h2>
                    {% else %}
                    <h2 class  = 'addComment center-align'>Add a new comment</h2>
                    <form action="." method="post">
                    {{ comment_form.as_p }}
                    {% csrf_token %}
                    <p><input type="submit" value="Add comment"></p>
                    </form>
                    {% endif %}

        </section>
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load static%}


{% block title %}My Blog{% endblock %}

{% block content %}

<section class="fslider">
        <div class="slider">
            <ul class="slides">
                
                <li>
                    <img src="{% static 'images/idea3.jpg' %}" alt="image1">
                    <div class="caption center-align white-text">
                        <h3>Real Simple</h3>
                        <h5 class="light text-lighten-3"> Ideas, Tips, and Simple Ways to Make Life Even Easie</h5>

                    </div>
                </li>
                <li>
                    <img src="{% static 'images/life2.jpg' %}" alt="image1">
                    <div class="caption center-align white-text">
                        <h3>Lifehacker:</h3>
                        <h5 class="light text-lighten-3"> Tips and downloads for getting things done</h5>

                    </div>
                </li>
                <li>
                    {% comment %} <img src='/static/images/samsung-memory-ngWKDQhM88Q-unsplash.jpg' alt="logo"  /> {% endcomment %}
                    <img src  = "{% static 'images/computer2.jpg' %}" />
                    
                    <div class="caption center-align white-text">
                        <h3>Computer</h3>
                        <h5 class="light text-lighten-3">Learn new Techonologies </h5>

                    </div>
                </li>
            </ul>
        </div>
</section>






  </div><div class="container-fluid">
        {% comment %} <h1 id="myblog" class="center-align">These are my blogs</h1> {% endcomment %}
        {% for post in posts %}
        
                    <div class="row">
                        <div class="col s12 m12 l4">
                        <div class="card hoverable deep-purple accent-3 z-depth-2">
                            <div class="card-content white-text">
                            <span class="card-title white-text ">{{ post.title }}</span>
                            <p>{{ post.body|truncatewords:30|linebreaks }}</p>
                            </div>
                            {% comment %} <br>
                            <br> {% endcomment %}
                            <hr class ="cardhr" > 
                            <div class="card-action">
                            <p class="carddate">
                            Published {{ post.publish }} by {{ post.author }}
                            </p>
                            <a class="btn tooltipped" data-position="bottom" data-tooltip="view full blog" id = 'carda'  class= 'center-align'  href="{{ post.get_absolute_url }}">Click ME</a>
                            
                            </div>
                        </div>
                        </div>
        {% comment %} <h2 id = absurl>
        <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
        </a>
        </h2>
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }} {% endcomment %}
        {% endfor %}

        <!-- This is for class based -->

            

        {% comment %} <section>
        <div class = 'fpagination center-align '>

            {% include "blog/pagination.html" with page=page_obj %} 
        </div>
        </section> {% endcomment %}
                    
        <!-- {% include "blog/pagination.html" with page=posts %}       This for function based -->
</div>

<section class = 'pagination'>
    <div class ='container fpagination center-align'>
        {% include "blog/pagination.html" with page=page_obj %} 
    </div>
</section>

<hr>

<section >
    <div class =' blogPicInfo container'> 
        <div class ='row'>
            <div class = 'col l6 sm12  left-align '>
                <img   src="{% static 'images/undraw_blogging_vpvv.svg' %}" height = '300' width = '500' alt="image1">           

            </div>
            <div class = 'col l6 sm12   '>
                <p class = 'blogInfo' >
                A blog (a truncation of "weblog")[1] is a discussion or informational website published on the World Wide Web consisting of discrete, often informal diary-style text entries (posts). Posts are typically displayed in reverse chronological order, so that the most recent post appears first, at the top of the web page. Until 2009, blogs were usually the work of a single individual,[citation needed] occasionally of a small group, and often covered a single subject or topic. In the 2010s, "multi-author blogs" (MABs) emerged, featuring the writing of multiple authors and sometimes professionally edited. MABs from newspapers, other media outlets, universities, think tanks, advocacy groups, and similar institutions account for an increasing quantity of blog traffic. The rise of Twitter and other "microblogging" systems helps integrate MABs and single-author blogs into the news media. Blog can also be used as a verb, meaning to maintain or add content to a blog
                </p>          

            </div>
        </div>

    </div>
    
</section>









{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
<div class = 'container'>
        {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
        "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
        {% else %}
        <h1 class = 'ByMail center-align'>Share "{{ post.title }}" By E-mail</h1>
        <div class = 'container'>
            <form action="." method="post">
            {{ form.as_p }}
            {% csrf_token %}
            {% comment %} <input type="submit" value="Send e-mail"> {% endcomment %}
            <div class = 'center-align'>
            <button class="btn waves-effect waves-light" type="submit" value = 'Send e-mail' name="action">Submit
                {% comment %} <i class="material-icons right">send</i> {% endcomment %}
            </button>
            </div>
        
            </form>
        </div>
        {% endif %}

</div>
{% endblock %}